name: MLOps CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install DVC
      run: |
        pip install dvc[gcs]

    - name: Pull DVC Data
      run: |
        dvc pull

    - name: Install Requirements
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest
